### ISSUE TITLE
Integrate kH Director

### ISSUE THREAD

**Issue by Alex-Beh** [brandjas/Profilux-InfluxDB#5]
May I know how you come out with the configuration in [sensordata.json](https://github.com/brandjas/Profilux-InfluxDB/blob/main/sensordata.json)? I would like to integrate the kH Director into the system but have no clue how to modify the json file.

It will be good if you can point me to the documentation that you refer to as well.

**Comment by brandjas** [comment]
Hi Alex, the variable replacement works as documented in [User designed web pages for ProfiLux 3 & 3.1](https://www.aquariumcomputer.com/downloads/user-designed-web-pages-for-profilux-3-3-1/). I don't have access to a kH Director so I'm not entirely sure whether its data can be accessed through these tokens
